---
#
# Ansible managed
#
repository:
  description: Install and configure jenkins on your system.
  homepage: https://robertdebock.nl/
  topics: jenkins, server, system, development, ansible, molecule, playbook
