---
# tasks file for jenkins
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: add yum repository
  get_url:
    url: "{{ jenkins_yum_repository_baseurl }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when:
    - ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum"

- name: import rpm key
  rpm_key:
    key: "{{ jenkins_rpm_key }}"
    state: present
    validate_certs: no
  when:
    - ansible_pkg_mgr in [ "dnf", "yum", "zypper" ]

- name: add apt key
  apt_key:
    url: "{{ jenkins_apt_key_url }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: add apt repository
  apt_repository:
    repo: "{{ jenkins_apt_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: add zypper repository
  zypper_repository:
    name: jenkins
    repo: "{{ jenkins_zypper_repository_repo }}"
    state: present
  when:
    - ansible_pkg_mgr == "zypper"

- name: install requirements
  package:
    name: "{{ jenkins_requirements }}"
    state: present

- name: install jenkins
  package:
    name: jenkins
    state: present

- name: configure jenkins
  template:
    src: jenkins.j2
    dest: "{{ jenkins_configuration_directory }}"
    mode: "0640"
  notify:
    - restart jenkins

- name: start and enable jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
